name: R script Karup 1

on: 
  push:
    paths:
      - .github/workflows/run_script_karup1.yaml
      - script_karup1.R
  schedule: 
    - cron: '0 * * * *'  # every hour
    
jobs:
  render:
    name: Run script_karup1.R
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@master
      - name: Install packages
        run: Rscript install.R
      - name: Run R script
        run: Rscript --verbose script_karup1.R
      - name: Commit results
        run: |
          git config user.email "junk@relund.dk"
          git config user.name "Lars Relund"
          git fetch origin
          git commit --allow-empty -am 'gHA build: ${{github.run_number}}' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.token}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
