name: R script Skjern 1

on: 
  push:
    paths:
      - .github/workflows/run_script_skjern1_ubuntu.yaml
      - script_skjern1.R
      - functions.R
  schedule: 
    - cron: '0 * * * *'  # every hour

jobs:
  render:
    name: Run script_skjern1.R
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      
      - name: Install pandoc
        uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true
    
      - name: Install dependices
        run: |
          sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update
          sudo apt-get install libgdal-dev libgeos-dev libproj-dev 
          
      - uses: r-lib/actions/setup-renv@v1
          
      - name: Run R script
        run: Rscript script_skjern1.R
        
      - name: Commit results
        run: |
          git config user.email "junk@relund.dk"
          git config user.name "Lars Relund"
          git add \*.csv
          git commit --allow-empty -am 'gHA build: ${{github.run_number}}' || echo "No changes to commit"
          git pull --rebase
          git push origin || echo "No changes to commit"
